import { Test, TestingModule } from '@nestjs/testing';
import { AuthController } from './auth.controller';
import { AuthService } from './auth.service';
import { TokenKeyService } from './token-key/token-key.service';

const mockTokenKeyService = {
  generateTokenKey: jest.fn(),
  validateAccessToken: jest.fn(),
  validateRefreshToken: jest.fn(),
  revokeToken: jest.fn(),
};

const mockAuthService = {};

describe('AuthController', () => {
  let authController: AuthController;

  beforeEach(async () => {
    const app: TestingModule = await Test.createTestingModule({
      controllers: [AuthController],
      providers: [
        { provide: AuthService, useValue: mockAuthService },
        { provide: TokenKeyService, useValue: mockTokenKeyService },
      ],
    }).compile();

    authController = app.get<AuthController>(AuthController);
    jest.clearAllMocks();
  });

  describe('createUserAuthToken', () => {
    it('should return tokens generated by tokenKeyService', async () => {
      const dto = { userId: '1', username: 'testuser' };
      const tokens = {
        accessToken: 'access-token',
        refreshToken: 'refresh-token',
      };
      mockTokenKeyService.generateTokenKey.mockResolvedValue(tokens);

      const result = await authController.createUserAuthToken(dto as any);

      expect(mockTokenKeyService.generateTokenKey).toHaveBeenCalledWith(dto);
      expect(result).toEqual(tokens);
    });
  });

  describe('validateAccessToken', () => {
    it('should return the validated token payload', async () => {
      const payload = { sub: 'testuser', tid: '1' };
      mockTokenKeyService.validateAccessToken.mockResolvedValue(payload);

      const result = await authController.validateAccessToken({
        token: 'access-token',
      });

      expect(mockTokenKeyService.validateAccessToken).toHaveBeenCalledWith(
        'access-token',
      );
      expect(result).toEqual(payload);
    });
  });

  describe('refreshAccessToken', () => {
    it('should return new tokens from refresh token', async () => {
      const tokens = { accessToken: 'new-access', refreshToken: 'new-refresh' };
      mockTokenKeyService.validateRefreshToken.mockResolvedValue(tokens);

      const result = await authController.refreshAccessToken({
        refreshToken: 'old-refresh',
      });

      expect(mockTokenKeyService.validateRefreshToken).toHaveBeenCalledWith(
        'old-refresh',
      );
      expect(result).toEqual(tokens);
    });
  });

  describe('logout', () => {
    it('should revoke the refresh token', async () => {
      mockTokenKeyService.revokeToken.mockResolvedValue(true);

      const result = await authController.logout({
        refreshToken: 'some-refresh-token',
      });

      expect(mockTokenKeyService.revokeToken).toHaveBeenCalledWith(
        'some-refresh-token',
      );
      expect(result).toBe(true);
    });
  });
});
