### =======================================================
### Auth MODULE - REST API TESTS
### =======================================================

### Variables
@baseUrl = http://localhost:3000/api
@register = {{baseUrl}}/user/register
@login = {{baseUrl}}/user/login
@profile = {{baseUrl}}/user/profile

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0aWQiOjcsInN1YiI6ImhvYWlfbmFydF81ayIsImlhdCI6MTc2NzA2MjIxNiwiZXhwIjoxNzY3MDYzMTE2fQ.t6BLzx3P0xhCKQj8XGsnRi-Sjektx672tyIChblp0lA
@refreshToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0aWQiOjcsInN1YiI6ImhvYWlfbmFydF81ayIsImlhdCI6MTc2NzA2Nzc3MCwiZXhwIjoxNzY3NjcyNTcwfQ.K_kWAdIRutiP61L3Tpn6YvL5LLaKl2tTkwhFdS4IkMk; Path=/; HttpOnly
### register 
POST {{register}}
Content-Type: application/json

{
  "username": "hoai_nart_5k",
  "email": "hoai.dev@gmail.com",
  "password": "123"
}


### Login 
POST {{login}}
Content-Type: application/json

{
  "username": "hoai_nart_5k",
  "password": "123"
}

### Get Profile
GET {{baseUrl}}/user/profile
Authorization: Bearer {{token}}

### Refresh Token
POST {{baseUrl}}/user/refresh-token
Content-Type: application/json
Authorization: Bearer {{token}}
Cookie: refresh_token={{refreshToken}}

### Test Order API
POST {{baseUrl}}/orders/test
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "userId": 1,
  "items": [
    { "productId": "2", "quantity": 1 },
    { "productId": "1", "quantity": 3 }
  ]
}

