### =======================================================
### Auth MODULE - REST API TESTS
### =======================================================

### Variables
@baseUrl = http://localhost:3000/api
@register = {{baseUrl}}/user/register
@login = {{baseUrl}}/user/login
@profile = {{baseUrl}}/user/profile

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0aWQiOjcsInN1YiI6ImhvYWlfbmFydF81ayIsImlhdCI6MTc2NjcyMDk5NCwiZXhwIjoxNzY2NzIxODk0fQ.TBoqCrz5T9YKeO0grVX1PRPamC-CMH585Z8g1llaJPc
### register 
POST {{register}}
Content-Type: application/json

{
  "username": "hoai_nart_5k",
  "email": "hoai.dev@gmail.com",
  "password": "123"
}


### Login 
POST {{login}}
Content-Type: application/json

{
  "username": "hoai_nart_5k",
  "password": "123"
}

### Get Profile
GET {{baseUrl}}/user/profile
Authorization: Bearer {{token}}


### Test Order API
POST {{baseUrl}}/orders/test
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "userId": 1,
  "items": [
    { "productId": "2", "quantity": 1 },
    { "productId": "1", "quantity": 3 }
  ]
}