### =======================================================
### Auth MODULE - REST API TESTS
### =======================================================

### Variables
@baseUrl = http://localhost:3000/api
@register = {{baseUrl}}/user/register

### register 
POST {{register}}
Content-Type: application/json

{
  "username": "hoai_nart_5k",
  "email": "hoai_nart_5k@gmail.com",
  "password": "123456",
}

