# ========== CONFIGURATION ==========
@baseUrl = http://localhost:3000/api
@contentType = application/json


### Place Order
POST {{baseUrl}}/orders
Content-Type: {{contentType}}

{
  "userId": 1,
  "items": [
    { "productId": "2", "quantity": 1 },
    { "productId": "1", "quantity": 3 }
  ]
}